### ISSUE TITLE
stubby does not show proper version information when selected in the macOS Finder

### ISSUE THREAD

**Issue by core-code** [Sinodun/stubby_manager_gui#3]
CFBundleShortVersionString and CFBundleVersion entries filled with the value '0.2.0' are missing

**Comment by saradickinson** [comment]
This is fixed in the latest installer (v0.2.6):
https://dnsprivacy.org/wiki/display/DP/Stubby+GUI+for+macOS
Please verify!

**Comment by core-code** [comment]
thanks, i've verified this, its solved!
